version: '3'

networks:
    laravel:

services:

    nginx:
        networks: 
            - laravel
        image: nginx:stable-alpine
        # container_name: webserver
        ports:
            - "8000:80"
        volumes:
            - ./lessclick:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php

    mysql:
        image: mysql:5.7.22
        # container_name: database
        restart: unless-stopped
        networks: 
            - laravel
        tty: true
        ports:
            - "1620:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: 
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql

    php:
        build: 
            context: ./
            dockerfile: Dockerfile
        networks:
            - laravel
        # container_name: php
        volumes:
            - ./lessclick:/var/www/html
            - ./supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
            - ./supervisor/horizon.conf:/etc/supervisor/conf.d/horizon.conf
        ports:
            - "9000:9000"
        # command: bash -c "php artisan horizon"
        depends_on: 
            - mysql
            - redis

    redis:
        image: 'redis:3.2-alpine'
        networks:
            - laravel
        volumes:
            - ./redis/data:/data:rw
        command: redis-server --appendonly yes
        ports:
            - "6379:6379"
